"""Remove existing merchant_id field

Revision ID: 2e18e1b7cfd1
Revises: 4c6e2c2eb02e
Create Date: 2022-02-26 11:09:41.152809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e18e1b7cfd1'
down_revision = '4c6e2c2eb02e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.drop_index('ix_merchant_merchant_id')
        batch_op.drop_column('merchant_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
        batch_op.create_index('ix_merchant_merchant_id', ['merchant_id'], unique=False)

    # ### end Alembic commands ###
