"""Adding uuid merchant_id to Merchant

Revision ID: 3c23a93867f6
Revises: 2e18e1b7cfd1
Create Date: 2022-02-26 11:12:43.723138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c23a93867f6'
down_revision = '2e18e1b7cfd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_id', postgresql.UUID(as_uuid=True), nullable=True))
        batch_op.create_unique_constraint(None, ['merchant_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('merchant_id')

    # ### end Alembic commands ###
