"""First migration- creating Merchant model

Revision ID: 4c6e2c2eb02e
Revises: 
Create Date: 2022-02-16 22:20:28.948472

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c6e2c2eb02e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.String(length=32), nullable=True),
    sa.Column('donation_configs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_merchant_merchant_id'), ['merchant_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merchant_merchant_id'))

    op.drop_table('merchant')
    # ### end Alembic commands ###
