"""Adding spl_wallet_address to Recipient

Revision ID: 6065628369dc
Revises: 0bc107621cdf
Create Date: 2022-02-26 11:37:56.343534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6065628369dc'
down_revision = '0bc107621cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spl_wallet_address', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipient', schema=None) as batch_op:
        batch_op.drop_column('spl_wallet_address')

    # ### end Alembic commands ###
