"""Add SplitTransactionRequest

Revision ID: 633278fc5533
Revises: 8bb8259192de
Create Date: 2022-03-01 21:15:28.684418

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '633278fc5533'
down_revision = '8bb8259192de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('split_transaction_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('spl_token', sa.String(length=64), nullable=True),
    sa.Column('recipient_public_key', sa.String(length=64), nullable=True),
    sa.Column('merchant_public_key', sa.String(length=64), nullable=True),
    sa.Column('merchant_amount', sa.Integer(), nullable=True),
    sa.Column('recipient_amount', sa.Integer(), nullable=True),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('recipient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipient', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    op.drop_table('split_transaction_request')
    # ### end Alembic commands ###
