"""Adding name field to Merchant class

Revision ID: 77d3bec02c80
Revises: 633278fc5533
Create Date: 2022-03-09 18:32:44.089216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77d3bec02c80'
down_revision = '633278fc5533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
