"""Change merchant_id to recipient_id in Recipient

Revision ID: 78f183308c16
Revises: 6065628369dc
Create Date: 2022-02-26 11:39:31.177136

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '78f183308c16'
down_revision = '6065628369dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_id', postgresql.UUID(as_uuid=True), nullable=True))
        batch_op.drop_constraint('recipient_merchant_id_key', type_='unique')
        batch_op.create_unique_constraint(None, ['recipient_id'])
        batch_op.drop_column('merchant_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_id', postgresql.UUID(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('recipient_merchant_id_key', ['merchant_id'])
        batch_op.drop_column('recipient_id')

    # ### end Alembic commands ###
