"""Create MarkedDonation

Revision ID: 8bb8259192de
Revises: 229e913f9225
Create Date: 2022-02-28 15:24:04.941510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8bb8259192de'
down_revision = '229e913f9225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marked_donation',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.Column('merchant_transaction_id', sa.String(length=64), nullable=True),
    sa.Column('donation_type', sa.String(length=64), nullable=True),
    sa.Column('donation_amount', sa.Integer(), nullable=True),
    sa.Column('purchase_total', sa.Integer(), nullable=True),
    sa.Column('transaction_total', sa.Integer(), nullable=True),
    sa.Column('merchant_public_key', sa.String(length=64), nullable=True),
    sa.Column('consumer_public_key', sa.String(length=64), nullable=True),
    sa.Column('recipient_public_key', sa.String(length=64), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marked_donation')
    # ### end Alembic commands ###
