"""Adding Consumer model

Revision ID: a46cea754b5e
Revises: 77d3bec02c80
Create Date: 2022-03-09 19:10:00.919878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a46cea754b5e'
down_revision = '77d3bec02c80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consumer')
    # ### end Alembic commands ###
